### ISSUE TITLE
No code that could recognise the sound and listen it?

### ISSUE THREAD

**Issue by shivambitm** [My-Personal-HUB/AI_Jarvis#2]
### use sr.Recognizer() for listening to the user..
def takeCommand():
    r=sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        audio=r.listen(source)
assign me for this @ayushii18

**Comment by ayushii18** [comment]
> ### use sr.Recognizer() for listening to the user..
> def takeCommand():
> r=sr.Recognizer()
> with sr.Microphone() as source:
> print("Listening...")
> audio=r.listen(source)
> assign me for this @ayushii18

@shivamkumar0611 please close this issue by tonight.
![siri2](https://user-images.githubusercontent.com/71550203/93667586-c7176080-faa4-11ea-8bef-a0e467f3eec0.jpg)

**Comment by sauravmandal255** [comment]
> > ### use sr.Recognizer() for listening to the user..
> > def takeCommand():
> > r=sr.Recognizer()
> > with sr.Microphone() as source:
> > print("Listening...")
> > audio=r.listen(source)
> > assign me for this @ayushii18
> 
> @shivamkumar0611 please close this issue by tonight.
> ![siri2](https://user-images.githubusercontent.com/71550203/93667586-c7176080-faa4-11ea-8bef-a0e467f3eec0.jpg)

I could also do this

**Comment by shivambitm** [comment]
This issue was solved by @santosh-sudo 
Here is the link for the same - https://github.com/My-Personal-HUB/AI_Jarvis/pull/6
Great work everyone.
