### ISSUE TITLE
System will crash if the user will ask to search something 

### ISSUE THREAD

**Issue by rohansahana6** [My-Personal-HUB/AI_Jarvis#4]
Like search wikipedia , open youtube , open Google 
There are many things that could be added here 
Assign me for this @shivamkumar0611 @ayushii18 @santosh-sudo

**Comment by ayushii18** [comment]
_Use If else statement for this purpose_

**Comment by shivambitm** [comment]
Okay I'll solve this issue @ayushii18

**Comment by ayushii18** [comment]
This issue was resolved and completed by @shivamkumar0611 here - https://github.com/My-Personal-HUB/AI_Jarvis/pull/9
